---
title: "导论"
author: "陈洁"
date: "2019/10/9"
output: html_document
---

# 第一章

## 1.1统计学习概述 

统计学习是一套以理解数据为目的的庞大工具集。统计学习的工具可分为两大类:有指导的学习（supervised learning）和无指导的学习（unsupervised learning），简单来说，有监督学习指使用的是有标签的数据（即实现分好类了），无监督学习指使用的数据时没有标签的。分类(Categorization or Classification)就是按照某种标准给对象贴标签(label)，再根据标签来区分归类，这属于有监督学习，还包括回归；聚类是指事先没有“标签”而通过某种成团分析找出事物之间存在聚集性原因的过程，这属于无监督学习。有一般而言，有指导的统计学习工具主要有两种用途:一是面向预测的统计模型的建立，二是
对一个或多个给定的输入估计某个输出。在无指导的统计学习问题中，有输入变量但不指定输出变量，建模的主旨是学习数据的关系和结构。


## 1.2记号与简单的矩阵代数
记号中，n表示不同数据点或样本观测的个数；p表示用于预测的变量个数。一般地，$x_{ij}代表第i个观测的第j个变量值,i = 1,2,{\ldots}, n;j = 1,{\ldots},p。在本书中i用于索引样本或观测（从1到n），j用于索引变量（从1到p）。\bf{X}则是(i,j)上元素为x_{ij}的n\times{p}$矩阵即

$$
        {X}=\begin{pmatrix}
        x_{11} & x_{12} & \cdots & x_{1p} \\
        x_{21} & x_{22} & \cdots & x_{2p} \\
        \vdots & \vdots & \ddots & \vdots \\
        x_{n1} & x_{n2} & \cdots & x_{np} \\
        \end{pmatrix}
$$
对矩阵不熟悉的读者，可将$\bf{X}$看成$n$行$p$列的表格。
有时会对$\bf{X}$的行进行研究，通常将行记为$x_1,x_2,{\ldots},x_n$。这里$x_i$是长度为$p$的向量，是第$i$个观测的$p$个变量测量，即
$$
        {x_i}=\begin{pmatrix}
        x_{i1} \\
        x_{i2} \\
        \vdots \\
        x_{ip} \\
        \end{pmatrix}
$$
（向量默认用列表示。）例如，对于 Wage数据集，$x_i$是一个长度为 11 的向量，包含第$i$个个体的year(年份)、age(年龄)、wage(工资)和其他变量值。有时也会研究$\bf{X}$的列，将其写作$x_1,x_2\cdots\ x_p$。它们都是长度为$n$的向量，即
$$
        {X_j}=\begin{pmatrix}
        x_{1j} \\
        x_{2j} \\
        \vdots \\
        x_{nj} \\
        \end{pmatrix}
$$


```{r,echo=TRUE,warning=FALSE}
library(ISLR)
attach(Wage)
head(Wage)
```


例如，Wage数据集中，$x_1$包含year（年份）的n=3000个观测值。
按这个记号，矩阵$\bf{X}$可以写成
           $$\bf{X}=(x_1\ x_2\cdots\ x_p)$$
或
$$
        {X}=\begin{pmatrix}
        x_{1}^T \\
        x_{2}^T \\
        \vdots \\
        x_{n}^T \\
        \end{pmatrix}
$$

右上角记号$T$表示矩阵或向量的转置。例如${x_i}^T=(x_{i1}\ x_{i2}\cdots\ x_{ip})$,以及
$$
        {X}^T=\begin{pmatrix}
        x_{11} & x_{21} & \cdots & x_{n1} \\
        x_{12} & x_{22} & \cdots & x_{n2} \\
        \vdots & \vdots & \ddots & \vdots \\
        x_{1p} & x_{2p} & \cdots & x_{np} \\
        \end{pmatrix}
$$
$y_i$表示待预测的变量(比如wage) 的第$i$个观测值。待预测变量全部 $n$个观测值的集合用如下向量表示:
$$
        y=\begin{pmatrix}
        y_{1} \\
        y_{2} \\
        \vdots \\
        y_{n} \\
        \end{pmatrix}
$$
观测数据集为$\lbrace(x_1,y_1),(x_2,y_2),\cdots,(x_n,y_n)\rbrace$，其中$x_i$都是长度为$p$的向量。（若$p=1$，则$x_i$是标量。）
在本书中，长度为$n$的向量均用小写加粗字母表示，例如：
$$
        \bf a=\begin{pmatrix}
        a_1 \\
        a_2 \\
        \vdots \\
        a_n \\
        \end{pmatrix}
$$



+ 长度不为$n$的向量则用小写常规字母表示，例如$a$。
+ 标量也用小写常规字母表示，例如$a$。
+ 矩阵用加粗大写字母表示，例如$\bf{A}$。
+ 随机变量不论维数，一律用大写常规字母表示，例如$A$。
有时需要指出对象的维数。记号$a\in{\Bbb R}$说明某个对象是标量（若长度为$n$,则用$a\in{\Bbb R}^n$表示）。$a\in{\Bbb R}^k$说明某对象为向量，其长度为$k$。$\bf{A}\in{\Bbb R}^{r\times s}$则说明矩阵的维数是$r\times s$。


在这些情况下，理解矩阵乘法的概念是很重要的。$\bf{A}\in{\Bbb R}^{r\times d}$，$\bf{B}\in{\Bbb R}^{d\times s}$。则$\bf{A}$与$\bf{B}$相乘的结果记为$\bf{AB}$。矩阵$\bf{AB}$的第$(i,j)$个元素等于$\bf{A}$中的第$i$行和$\bf{B}$中的第$j$列的对应元素乘积之和。即$(\bf{AB})_{ij}=\sum_{k=1}^d a_{ik}b_{kj}$。





